In [82]:
import numpy as np
import pandas as pd

In [83]:
pd.__version__

'3.0.5'

In [84]:
df = pd.read_csv(r"car_fuel_efficiency_2026.csv")

In [85]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_year           10000 non-null  int64
 1   origin               10000 non-null  str
 2   fuel_type            10000 non-null  str
 3   drivetrain           10000 non-null  str
 4   num_doors            10000 non-null  int64
 5   engine_displacement  10000 non-null  int64
 6   num_cylinders        10000 non-null  int64
 7   horsepower           9123 non-null   float64
 8   vehicle_weight       10000 non-null  int64
 9   acceleration         9736 non-null   float64
 10  fuel_efficiency_mpg  10000 non-null  float64
dtypes: float64(3), int64(5), str(3)
memory usage: 859.5 KB

In [86]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [87]:
df['fuel_type'].nunique()

3

In [88]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [89]:
df_asia = df[df['origin'] == 'Asia']
df_asia['fuel_efficiency_mpg'].max()

np.float64(41.2)

In [90]:
df['horsepower'].median()

np.float64(254.0)

In [91]:
df['horsepower'].isnull().sum()

np.int64(877)

In [92]:
df['horsepower'].mode()

0    252.0
Name: horsepower, dtype: float64

In [93]:
df['horsepower'] = df['horsepower'].fillna(252)
df['horsepower'].isnull().sum()

np.int64(0)

In [94]:
df['horsepower'].median()

np.float64(252.0)

In [95]:
df_asia = df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']].head(7)

In [96]:
df_asia

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [97]:
X = np.array(df_asia)

In [98]:
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [99]:
XTX = X.T @ X
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [100]:
inv_XTX = np.linalg.inv(XTX)
inv_XTX

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [101]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
w = inv_XTX @ X.T @ y
w

array([0.13644777, 0.2327492 ])

In [102]:
np.sum(w)

np.float64(0.3691969690492751)